openapi: 3.0.3
info:
  title: Product Management API
  version: 1.0.0
  description: Machine Test Submission - Production-ready Product API
paths:
  /api/categories/:
    get:
      operationId: api_categories_retrieve
      summary: List Categories
      tags:
      - api
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CategoryListResponse'
          description: ''
    post:
      operationId: api_categories_create
      summary: Create Category
      tags:
      - api
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Category'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/Category'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/Category'
        required: true
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '201':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CategoryCreateResponse'
          description: ''
        '400':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CategoryCreateErrorResponse'
          description: ''
  /api/categories/{slug}/:
    get:
      operationId: api_categories_retrieve_2
      summary: Get Category Details
      parameters:
      - in: path
        name: slug
        schema:
          type: string
        required: true
      tags:
      - api
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CategoryDetailResponse'
          description: ''
    put:
      operationId: api_categories_update
      summary: Update Category
      parameters:
      - in: path
        name: slug
        schema:
          type: string
        required: true
      tags:
      - api
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Category'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/Category'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/Category'
        required: true
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CategoryUpdateResponse'
          description: ''
        '400':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CategoryUpdateErrorResponse'
          description: ''
    delete:
      operationId: api_categories_destroy
      summary: Delete Category
      parameters:
      - in: path
        name: slug
        schema:
          type: string
        required: true
      tags:
      - api
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '204':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CategoryDeleteResponse'
          description: ''
  /api/products/:
    get:
      operationId: api_products_retrieve
      summary: List Products
      tags:
      - api
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProductListResponse'
          description: ''
    post:
      operationId: api_products_create
      summary: Create Product
      tags:
      - api
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Product'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/Product'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/Product'
        required: true
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '201':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProductCreateResponse'
          description: ''
        '400':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProductCreateErrorResponse'
          description: ''
  /api/products/{slug}/:
    get:
      operationId: api_products_retrieve_2
      summary: Get Product Details
      parameters:
      - in: path
        name: slug
        schema:
          type: string
        required: true
      tags:
      - api
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProductDetailResponse'
          description: ''
    put:
      operationId: api_products_update
      summary: Update Product
      parameters:
      - in: path
        name: slug
        schema:
          type: string
        required: true
      tags:
      - api
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Product'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/Product'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/Product'
        required: true
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProductUpdateResponse'
          description: ''
        '400':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProductUpdateErrorResponse'
          description: ''
    delete:
      operationId: api_products_destroy
      summary: Delete Product
      parameters:
      - in: path
        name: slug
        schema:
          type: string
        required: true
      tags:
      - api
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '204':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProductDeleteResponse'
          description: ''
  /health/:
    get:
      operationId: health_retrieve
      tags:
      - health
      responses:
        '200':
          description: No response body
components:
  schemas:
    Category:
      type: object
      properties:
        id:
          type: string
          format: uuid
          readOnly: true
        name:
          type: string
          maxLength: 255
        slug:
          type: string
        created_at:
          type: string
          format: date-time
          readOnly: true
        updated_at:
          type: string
          format: date-time
          readOnly: true
      required:
      - created_at
      - id
      - name
      - updated_at
    CategoryCreateErrorResponse:
      type: object
      properties:
        data:
          type: object
          additionalProperties: {}
          nullable: true
        errors:
          type: object
          additionalProperties: {}
      required:
      - errors
    CategoryCreateResponse:
      type: object
      properties:
        data:
          $ref: '#/components/schemas/Category'
        errors:
          type: object
          additionalProperties: {}
          nullable: true
      required:
      - data
    CategoryDeleteResponse:
      type: object
      properties:
        data:
          type: object
          additionalProperties: {}
          nullable: true
        errors:
          type: object
          additionalProperties: {}
          nullable: true
        message:
          type: string
      required:
      - message
    CategoryDetailResponse:
      type: object
      properties:
        data:
          $ref: '#/components/schemas/Category'
        errors:
          type: object
          additionalProperties: {}
          nullable: true
      required:
      - data
    CategoryListResponse:
      type: object
      properties:
        data:
          type: array
          items:
            $ref: '#/components/schemas/Category'
        errors:
          type: object
          additionalProperties: {}
          nullable: true
      required:
      - data
    CategoryUpdateErrorResponse:
      type: object
      properties:
        data:
          type: object
          additionalProperties: {}
          nullable: true
        errors:
          type: object
          additionalProperties: {}
      required:
      - errors
    CategoryUpdateResponse:
      type: object
      properties:
        data:
          $ref: '#/components/schemas/Category'
        errors:
          type: object
          additionalProperties: {}
          nullable: true
      required:
      - data
    Product:
      type: object
      properties:
        id:
          type: string
          format: uuid
          readOnly: true
        name:
          type: string
          maxLength: 255
        slug:
          type: string
        description:
          type: string
          nullable: true
        price:
          type: string
          format: decimal
          pattern: ^-?\d{0,8}(?:\.\d{0,2})?$
        stock:
          type: integer
          maximum: 2147483647
          minimum: 0
        category:
          type: string
          nullable: true
        category_name:
          type: string
          readOnly: true
        image:
          type: string
          format: uri
          nullable: true
        thumbnail:
          type: string
          format: uri
          readOnly: true
          nullable: true
        is_active:
          type: boolean
          readOnly: true
        created_at:
          type: string
          format: date-time
          readOnly: true
        updated_at:
          type: string
          format: date-time
          readOnly: true
      required:
      - category_name
      - created_at
      - id
      - is_active
      - name
      - price
      - stock
      - thumbnail
      - updated_at
    ProductCreateErrorResponse:
      type: object
      properties:
        data:
          type: object
          additionalProperties: {}
          nullable: true
        errors:
          type: object
          additionalProperties: {}
      required:
      - errors
    ProductCreateResponse:
      type: object
      properties:
        data:
          $ref: '#/components/schemas/Product'
        errors:
          type: object
          additionalProperties: {}
          nullable: true
      required:
      - data
    ProductDeleteResponse:
      type: object
      properties:
        data:
          type: object
          additionalProperties: {}
          nullable: true
        errors:
          type: object
          additionalProperties: {}
          nullable: true
        message:
          type: string
      required:
      - message
    ProductDetailResponse:
      type: object
      properties:
        data:
          $ref: '#/components/schemas/Product'
        errors:
          type: object
          additionalProperties: {}
          nullable: true
      required:
      - data
    ProductListResponse:
      type: object
      properties:
        data:
          type: array
          items:
            $ref: '#/components/schemas/Product'
        errors:
          type: object
          additionalProperties: {}
          nullable: true
      required:
      - data
    ProductUpdateErrorResponse:
      type: object
      properties:
        data:
          type: object
          additionalProperties: {}
          nullable: true
        errors:
          type: object
          additionalProperties: {}
      required:
      - errors
    ProductUpdateResponse:
      type: object
      properties:
        data:
          $ref: '#/components/schemas/Product'
        errors:
          type: object
          additionalProperties: {}
          nullable: true
      required:
      - data
  securitySchemes:
    basicAuth:
      type: http
      scheme: basic
    cookieAuth:
      type: apiKey
      in: cookie
      name: sessionid
